import { colors } from "./colors";

export const WIZARD_STEPS = [
  "Dificuldade",
  "Piloto",
  "Histórico",
  "Categoria",
  "Equipe",
  "Confirmação",
];

export const DIFFICULTIES = [
  { id: "facil", name: "Facil", emoji: "😊", desc: "IA skill 20-60", accent: colors.VERDE },
  { id: "medio", name: "Medio", emoji: "😐", desc: "IA skill 30-80", accent: colors.AMARELO },
  { id: "dificil", name: "Dificil", emoji: "😤", desc: "IA skill 50-90", accent: colors.LARANJA },
  { id: "lendario", name: "Lendario", emoji: "💀", desc: "IA skill 70-100", accent: colors.VERMELHO },
];

export const NATIONALITIES = [
  { id: "br", label: "🇧🇷 Brasileiro", labelFem: "🇧🇷 Brasileira" },
  { id: "gb", label: "🇬🇧 Britanico", labelFem: "🇬🇧 Britanica" },
  { id: "de", label: "🇩🇪 Alemao", labelFem: "🇩🇪 Alema" },
  { id: "fr", label: "🇫🇷 Frances", labelFem: "🇫🇷 Francesa" },
  { id: "it", label: "🇮🇹 Italiano", labelFem: "🇮🇹 Italiana" },
  { id: "es", label: "🇪🇸 Espanhol", labelFem: "🇪🇸 Espanhola" },
  { id: "nl", label: "🇳🇱 Holandes", labelFem: "🇳🇱 Holandesa" },
  { id: "au", label: "🇦🇺 Australiano", labelFem: "🇦🇺 Australiana" },
  { id: "jp", label: "🇯🇵 Japones", labelFem: "🇯🇵 Japonesa" },
  { id: "us", label: "🇺🇸 Americano", labelFem: "🇺🇸 Americana" },
  { id: "mx", label: "🇲🇽 Mexicano", labelFem: "🇲🇽 Mexicana" },
  { id: "ar", label: "🇦🇷 Argentino", labelFem: "🇦🇷 Argentina" },
  { id: "fi", label: "🇫🇮 Finlandes", labelFem: "🇫🇮 Finlandesa" },
  { id: "be", label: "🇧🇪 Belga", labelFem: "🇧🇪 Belga" },
  { id: "pt", label: "🇵🇹 Portugues", labelFem: "🇵🇹 Portuguesa" },
  { id: "ca", label: "🇨🇦 Canadense", labelFem: "🇨🇦 Canadense" },
  { id: "at", label: "🇦🇹 Austriaco", labelFem: "🇦🇹 Austriaca" },
  { id: "ch", label: "🇨🇭 Suico", labelFem: "🇨🇭 Suica" },
  { id: "dk", label: "🇩🇰 Dinamarques", labelFem: "🇩🇰 Dinamarquesa" },
  { id: "se", label: "🇸🇪 Sueco", labelFem: "🇸🇪 Sueca" },
  { id: "no", label: "🇳🇴 Noruegues", labelFem: "🇳🇴 Norueguesa" },
  { id: "pl", label: "🇵🇱 Polones", labelFem: "🇵🇱 Polonesa" },
  { id: "cn", label: "🇨🇳 Chines", labelFem: "🇨🇳 Chinesa" },
];

export const STARTING_CATEGORIES = [
  {
    id: "mazda_rookie",
    name: "Mazda MX-5 Rookie Cup",
    car: "Mazda MX-5 2016",
    emoji: "🔴",
    teams: 6,
    races: 5,
    drivers: 12,
    description: "Categoria de entrada para aprender leitura de corrida, pista e consistência.",
  },
  {
    id: "toyota_rookie",
    name: "Toyota GR86 Rookie Cup",
    car: "Toyota GR86",
    emoji: "⚪",
    teams: 6,
    races: 5,
    drivers: 12,
    description: "Categoria de entrada com o mesmo tamanho de grid e foco total em fundamentos.",
  },
];

export const TEAM_PREVIEWS = {
  mazda_rookie: [
    { index: 0, name: "Racing Academy Red", shortName: "RAR", primaryColor: "#e63946", secondaryColor: "#e63946", country: "🇺🇸 EUA", performanceRating: 68 },
    { index: 1, name: "Rolling Thunder Academy", shortName: "RTA", primaryColor: "#2f3542", secondaryColor: "#2f3542", country: "🇺🇸 EUA", performanceRating: 74 },
    { index: 2, name: "Grid Start Racing School", shortName: "GSR", primaryColor: "#f6c90e", secondaryColor: "#f6c90e", country: "🇬🇧 Reino Unido", performanceRating: 60 },
    { index: 3, name: "First Gear Motorsport", shortName: "FGM", primaryColor: "#3a86ff", secondaryColor: "#3a86ff", country: "🇩🇪 Alemanha", performanceRating: 71 },
    { index: 4, name: "Apex Academy Racing", shortName: "AAR", primaryColor: "#2ec4b6", secondaryColor: "#2ec4b6", country: "🇫🇷 Franca", performanceRating: 78 },
    { index: 5, name: "Rookie Squad Racing", shortName: "RSQ", primaryColor: "#9b5de5", secondaryColor: "#9b5de5", country: "🇯🇵 Japao", performanceRating: 64 },
  ],
  toyota_rookie: [
    { index: 0, name: "Sakura Driver Academy", shortName: "SDA", primaryColor: "#d90429", secondaryColor: "#d90429", country: "🇯🇵 Japao", performanceRating: 74 },
    { index: 1, name: "Kanzen Racing School", shortName: "KRS", primaryColor: "#264653", secondaryColor: "#264653", country: "🇯🇵 Japao", performanceRating: 78 },
    { index: 2, name: "Open Road Academy", shortName: "ORA", primaryColor: "#8b5e34", secondaryColor: "#8b5e34", country: "🇺🇸 EUA", performanceRating: 64 },
    { index: 3, name: "Speed Lab Rookies", shortName: "SLR", primaryColor: "#fb5607", secondaryColor: "#fb5607", country: "🇺🇸 EUA", performanceRating: 68 },
    { index: 4, name: "Rising Stars Motorsport", shortName: "RSM", primaryColor: "#ffbe0b", secondaryColor: "#ffbe0b", country: "🇬🇧 Reino Unido", performanceRating: 71 },
    { index: 5, name: "Fresh Start Racing", shortName: "FSR", primaryColor: "#80b918", secondaryColor: "#80b918", country: "🇩🇪 Alemanha", performanceRating: 60 },
  ],
};

export const LOADING_MESSAGE_INTERVAL_MS = 2000;

export const LOADING_MESSAGES = [
  "Abrindo a base do paddock em 2000...",
  "Separando garagens, boxes e calendários iniciais...",
  "Distribuindo equipes pelas primeiras categorias...",
  "Montando a base de pilotos do ano 2000...",
  "Criando contratos iniciais para o grid histórico...",
  "Conferindo licenças antes da primeira temporada...",
  "Organizando calendários por categoria...",
  "Preparando as primeiras temporadas para largada...",
  "Simulando o início do arquivo corrida a corrida...",
  "Registrando os primeiros vencedores do arquivo histórico...",
  "Atualizando pontos e tabelas da temporada inicial...",
  "Fechando os campeonatos inaugurais do save...",
  "Abrindo a janela de evolução dos pilotos...",
  "Aplicando ganhos de experiência da primeira era...",
  "Movimentando contratos entre equipes rivais...",
  "Avaliando renovações e vagas abertas no mercado...",
  "Chamando rookies para completar o paddock...",
  "Registrando aposentadorias do ciclo histórico...",
  "Calculando promoções e rebaixamentos iniciais...",
  "Reorganizando categorias após o primeiro corte...",
  "Preparando o calendário da temporada seguinte...",
  "Simulando a era de consolidação do grid...",
  "Registrando duelos que viram memória de paddock...",
  "Atualizando rivalidades sem apressar a história...",
  "Processando lesões e retornos de pilotos...",
  "Conferindo equipes que subiram de patamar...",
  "Rebaixando estruturas que perderam fôlego esportivo...",
  "Recalculando reputações após cada campeonato...",
  "Arquivando resultados por temporada...",
  "Guardando poles, pódios e vitórias no histórico...",
  "Avançando pelo miolo da simulação histórica...",
  "Simulando calendários completos por categoria...",
  "Persistindo resultados corrida a corrida...",
  "Atualizando estatísticas de carreira dos pilotos...",
  "Somando pontos históricos das equipes...",
  "Construindo campeões de pilotos e construtores...",
  "Renovando lineups para a próxima rodada de anos...",
  "Abrindo novas vagas para jovens promessas...",
  "Retirando veteranos do grid ativo...",
  "Mantendo o mercado coerente entre temporadas...",
  "Aplicando promoções e rebaixamentos de meio ciclo...",
  "Reequilibrando grids depois das mudanças de categoria...",
  "Criando calendários para a reta final do passado...",
  "Simulando temporadas recentes do arquivo...",
  "Gravando corridas decisivas do ciclo histórico...",
  "Atualizando rivalidades que seguem vivas...",
  "Processando lesões históricas com efeito no grid...",
  "Conferindo contratos ativos após cada virada de ano...",
  "Repondo vagas antes da próxima temporada...",
  "Arquivando campanhas de pilotos aposentados...",
  "Consolidando memória esportiva das equipes...",
  "Fechando títulos e estatísticas acumuladas...",
  "Validando categorias disponíveis para o jogador...",
  "Separando equipes elegíveis para a estreia...",
  "Limpando notícias antigas do rascunho histórico...",
  "Removendo artefatos temporários da simulação...",
  "Normalizando o retrato financeiro para o início jogável...",
  "Preservando resultados sem carregar dívidas antigas...",
  "Recalculando o estado atual das equipes...",
  "Conferindo se o jogador ainda não entrou no mundo...",
  "Preparando o ano jogável de 2025...",
  "Abrindo o grid de 2025 com o passado completo...",
  "Organizando categorias rookies para escolha inicial...",
  "Listando equipes disponíveis para a primeira assinatura...",
  "Separando pilotos N1 e N2 das equipes de entrada...",
  "Conferindo nomes e cores das equipes de 2025...",
  "Atualizando o progresso do rascunho histórico...",
  "Validando o save antes de liberar a escolha...",
  "Fechando a última auditoria do calendário...",
  "Sincronizando contadores internos do banco...",
  "Preparando a tela de categorias iniciais...",
  "Carregando as opções de equipe para 2025...",
  "Deixando o paddock pronto para sua chegada...",
  "Finalizando o rascunho histórico do save...",
  "Entregando um mundo com passado antes da estreia...",
];
