// GERADO por scripts/gen-track-countries.mjs — não editar à mão.
// Mapa nome→país (com bandeira), de src-tauri/src/constants/tracks/dados.rs. Inclui nome
// completo, nome do local (antes de " - ") e nome curto, para casar com o track_name
// que o calendário guardar (ver split_track_name em calendar/montagem.rs).
export const TRACK_COUNTRIES = {
  "Adelaide": "🇦🇺 Austrália",
  "Adelaide Street Circuit": "🇦🇺 Austrália",
  "Algarve International Circuit": "🇵🇹 Portugal",
  "Algarve International Circuit - Grand Prix": "🇵🇹 Portugal",
  "Algarve International Circuit - Grand Prix Chicanes": "🇵🇹 Portugal",
  "Aragón": "🇪🇸 Espanha",
  "Aragón Natl": "🇪🇸 Espanha",
  "Autódromo Hermanos Rodríguez": "🇲🇽 México",
  "Autódromo Hermanos Rodríguez - Grand Prix": "🇲🇽 México",
  "Autódromo Hermanos Rodríguez - National": "🇲🇽 México",
  "Autodromo Internazionale del Mugello": "🇮🇹 Itália",
  "Autodromo Internazionale del Mugello - Grand Prix": "🇮🇹 Itália",
  "Autodromo Internazionale del Mugello - Short": "🇮🇹 Itália",
  "Autodromo Internazionale Enzo e Dino Ferrari": "🇮🇹 Itália",
  "Autodromo Internazionale Enzo e Dino Ferrari - Grand Prix": "🇮🇹 Itália",
  "Autódromo José Carlos Pace": "🇧🇷 Brasil",
  "Autódromo José Carlos Pace - Grand Prix": "🇧🇷 Brasil",
  "Autodromo Nazionale Monza": "🇮🇹 Itália",
  "Autodromo Nazionale Monza - Combined": "🇮🇹 Itália",
  "Autodromo Nazionale Monza - GP without chicanes": "🇮🇹 Itália",
  "Autodromo Nazionale Monza - GP without first chicane": "🇮🇹 Itália",
  "Autodromo Nazionale Monza - Grand Prix": "🇮🇹 Itália",
  "Barber": "🇺🇸 EUA",
  "Barber Motorsports Park": "🇺🇸 EUA",
  "Barcelona": "🇪🇸 Espanha",
  "Barcelona Natl": "🇪🇸 Espanha",
  "Bathurst": "🇦🇺 Austrália",
  "Belle Isle": "🇺🇸 EUA",
  "Brands GP": "🇬🇧 Reino Unido",
  "Brands Hatch Circuit": "🇬🇧 Reino Unido",
  "Brands Hatch Circuit - Grand Prix": "🇬🇧 Reino Unido",
  "Cadwell Park": "🇬🇧 Reino Unido",
  "Cadwell Park Circuit": "🇬🇧 Reino Unido",
  "Cadwell Park Circuit - Full": "🇬🇧 Reino Unido",
  "Canadian Tire Motorsport Park": "🇨🇦 Canadá",
  "Charlotte Motor Speedway": "🇺🇸 EUA",
  "Charlotte Motor Speedway - Roval 2025": "🇺🇸 EUA",
  "Charlotte Roval": "🇺🇸 EUA",
  "Chicago Street": "🇺🇸 EUA",
  "Chicago Street Course": "🇺🇸 EUA",
  "Chicago Street Course - Prototype": "🇺🇸 EUA",
  "Circuit de Barcelona-Catalunya": "🇪🇸 Espanha",
  "Circuit de Barcelona-Catalunya - Grand Prix": "🇪🇸 Espanha",
  "Circuit de Barcelona-Catalunya - National": "🇪🇸 Espanha",
  "Circuit de Lédenon": "🇫🇷 França",
  "Circuit de Nevers Magny-Cours": "🇫🇷 França",
  "Circuit de Spa-Francorchamps": "🇧🇪 Bélgica",
  "Circuit de Spa-Francorchamps - Endurance": "🇧🇪 Bélgica",
  "Circuit de Spa-Francorchamps - Grand Prix Pits": "🇧🇪 Bélgica",
  "Circuit des 24 Heures du Mans": "🇫🇷 França",
  "Circuit Gilles Villeneuve": "🇨🇦 Canadá",
  "Circuit of the Americas": "🇺🇸 EUA",
  "Circuit of the Americas - Grand Prix": "🇺🇸 EUA",
  "Circuit Zandvoort": "🇳🇱 Holanda",
  "Circuit Zandvoort - Grand Prix": "🇳🇱 Holanda",
  "Circuit Zandvoort - Grand Prix w/chicane": "🇳🇱 Holanda",
  "Circuit Zandvoort - Nationaal": "🇳🇱 Holanda",
  "Circuit Zolder": "🇧🇪 Bélgica",
  "Circuit Zolder - Grand Prix": "🇧🇪 Bélgica",
  "Circuito de Jerez": "🇪🇸 Espanha",
  "Circuito de Jerez - Ángel Nieto - Grand Prix": "🇪🇸 Espanha",
  "Circuito de Navarra": "🇪🇸 Espanha",
  "Circuito de Navarra - Speed Circuit": "🇪🇸 Espanha",
  "Circuito de Navarra - Speed Circuit Medium": "🇪🇸 Espanha",
  "Circuito de Navarra - Speed Circuit Short": "🇪🇸 Espanha",
  "Coronado": "🇺🇸 EUA",
  "COTA": "🇺🇸 EUA",
  "Daytona International Speedway": "🇺🇸 EUA",
  "Daytona International Speedway - Road Course": "🇺🇸 EUA",
  "Daytona Road": "🇺🇸 EUA",
  "Detroit Grand Prix at Belle Isle": "🇺🇸 EUA",
  "Donington GP": "🇬🇧 Reino Unido",
  "Donington Park Racing Circuit": "🇬🇧 Reino Unido",
  "Donington Park Racing Circuit - Grand Prix": "🇬🇧 Reino Unido",
  "Fuji": "🇯🇵 Japão",
  "Fuji International Speedway": "🇯🇵 Japão",
  "Fuji International Speedway - Grand Prix": "🇯🇵 Japão",
  "Fuji International Speedway - No Chicane": "🇯🇵 Japão",
  "Fuji No Chicane": "🇯🇵 Japão",
  "Hockenheim": "🇩🇪 Alemanha",
  "Hockenheimring Baden-Württemberg": "🇩🇪 Alemanha",
  "Hockenheimring Baden-Württemberg - Grand Prix": "🇩🇪 Alemanha",
  "Hungaroring": "🇭🇺 Hungria",
  "Imola": "🇮🇹 Itália",
  "Indianapolis Motor Speedway": "🇺🇸 EUA",
  "Indianapolis Motor Speedway - Road Course": "🇺🇸 EUA",
  "Indy Road": "🇺🇸 EUA",
  "Interlagos": "🇧🇷 Brasil",
  "Jerez": "🇪🇸 Espanha",
  "Knockhill": "🇬🇧 Reino Unido",
  "Knockhill Racing Circuit": "🇬🇧 Reino Unido",
  "Knockhill Racing Circuit - International": "🇬🇧 Reino Unido",
  "Laguna Seca": "🇺🇸 EUA",
  "Le Mans": "🇫🇷 França",
  "Lédenon": "🇫🇷 França",
  "Lime Rock": "🇺🇸 EUA",
  "Lime Rock Chicanes": "🇺🇸 EUA",
  "Lime Rock Classic": "🇺🇸 EUA",
  "Lime Rock Park": "🇺🇸 EUA",
  "Lime Rock Park - Chicanes": "🇺🇸 EUA",
  "Lime Rock Park - Classic": "🇺🇸 EUA",
  "Lime Rock Park - Grand Prix": "🇺🇸 EUA",
  "Long Beach": "🇺🇸 EUA",
  "Long Beach Street Circuit": "🇺🇸 EUA",
  "Magny-Cours": "🇫🇷 França",
  "Mexico City": "🇲🇽 México",
  "Mexico National": "🇲🇽 México",
  "Miami": "🇺🇸 EUA",
  "Miami International Autodrome": "🇺🇸 EUA",
  "Miami International Autodrome - Grand Prix": "🇺🇸 EUA",
  "Mid-Ohio": "🇺🇸 EUA",
  "Mid-Ohio Chicane": "🇺🇸 EUA",
  "Mid-Ohio Sports Car Course": "🇺🇸 EUA",
  "Mid-Ohio Sports Car Course - Chicane": "🇺🇸 EUA",
  "Mid-Ohio Sports Car Course - Full Course": "🇺🇸 EUA",
  "Misano": "🇮🇹 Itália",
  "Misano World Circuit Marco Simoncelli": "🇮🇹 Itália",
  "Misano World Circuit Marco Simoncelli - Grand Prix": "🇮🇹 Itália",
  "Mobility Resort Motegi": "🇯🇵 Japão",
  "Mobility Resort Motegi - Grand Prix": "🇯🇵 Japão",
  "Montreal": "🇨🇦 Canadá",
  "Monza": "🇮🇹 Itália",
  "Monza Combined": "🇮🇹 Itália",
  "Monza s/ 1ª chicane": "🇮🇹 Itália",
  "Monza s/ chicanes": "🇮🇹 Itália",
  "Mosport": "🇨🇦 Canadá",
  "Motegi": "🇯🇵 Japão",
  "MotorLand Aragón": "🇪🇸 Espanha",
  "MotorLand Aragón - Grand Prix": "🇪🇸 Espanha",
  "MotorLand Aragón - National": "🇪🇸 Espanha",
  "Motorsport Arena Oschersleben": "🇩🇪 Alemanha",
  "Motorsport Arena Oschersleben - Alternate": "🇩🇪 Alemanha",
  "Motorsport Arena Oschersleben - B Course": "🇩🇪 Alemanha",
  "Motorsport Arena Oschersleben - Grand Prix": "🇩🇪 Alemanha",
  "Mount Panorama Circuit": "🇦🇺 Austrália",
  "Mugello": "🇮🇹 Itália",
  "Mugello Short": "🇮🇹 Itália",
  "Navarra": "🇪🇸 Espanha",
  "Navarra Medium": "🇪🇸 Espanha",
  "Navarra Short": "🇪🇸 Espanha",
  "Nordschleife": "🇩🇪 Alemanha",
  "Nürburgring 24h": "🇩🇪 Alemanha",
  "Nürburgring Combined": "🇩🇪 Alemanha",
  "Nürburgring Combined - Gesamtstrecke 24h": "🇩🇪 Alemanha",
  "Nürburgring Combined - Gesamtstrecke Short w/out Arena": "🇩🇪 Alemanha",
  "Nürburgring Nordschleife": "🇩🇪 Alemanha",
  "Nürburgring Nordschleife - Industriefahrten": "🇩🇪 Alemanha",
  "Okayama": "🇯🇵 Japão",
  "Okayama International Circuit": "🇯🇵 Japão",
  "Okayama International Circuit - Full Course": "🇯🇵 Japão",
  "Okayama International Circuit - Short": "🇯🇵 Japão",
  "Okayama Short": "🇯🇵 Japão",
  "Oran Park": "🇦🇺 Austrália",
  "Oran Park North": "🇦🇺 Austrália",
  "Oran Park Raceway": "🇦🇺 Austrália",
  "Oran Park Raceway - Grand Prix": "🇦🇺 Austrália",
  "Oran Park Raceway - North": "🇦🇺 Austrália",
  "Oran Park Raceway - South": "🇦🇺 Austrália",
  "Oran Park South": "🇦🇺 Austrália",
  "Oschersleben": "🇩🇪 Alemanha",
  "Oschersleben Alt": "🇩🇪 Alemanha",
  "Oschersleben B": "🇩🇪 Alemanha",
  "Oulton Fosters": "🇬🇧 Reino Unido",
  "Oulton Intl": "🇬🇧 Reino Unido",
  "Oulton Island": "🇬🇧 Reino Unido",
  "Oulton Park Circuit": "🇬🇧 Reino Unido",
  "Oulton Park Circuit - Fosters": "🇬🇧 Reino Unido",
  "Oulton Park Circuit - International": "🇬🇧 Reino Unido",
  "Oulton Park Circuit - Intl w/no Chicanes": "🇬🇧 Reino Unido",
  "Oulton Park Circuit - Intl w/out Brittens": "🇬🇧 Reino Unido",
  "Oulton Park Circuit - Intl w/out Hislop": "🇬🇧 Reino Unido",
  "Oulton Park Circuit - Island": "🇬🇧 Reino Unido",
  "Oulton w/no Chicanes": "🇬🇧 Reino Unido",
  "Oulton w/out Brittens": "🇬🇧 Reino Unido",
  "Oulton w/out Hislop": "🇬🇧 Reino Unido",
  "Phillip Island": "🇦🇺 Austrália",
  "Phillip Island Circuit": "🇦🇺 Austrália",
  "Portimão": "🇵🇹 Portugal",
  "Portimão Chicanes": "🇵🇹 Portugal",
  "Portland": "🇺🇸 EUA",
  "Portland International Raceway": "🇺🇸 EUA",
  "Portland International Raceway - Full Circuit": "🇺🇸 EUA",
  "Qualcomm Circuit (Naval Base Coronado)": "🇺🇸 EUA",
  "Red Bull Ring": "🇦🇹 Áustria",
  "Red Bull Ring - Grand Prix": "🇦🇹 Áustria",
  "Road America": "🇺🇸 EUA",
  "Road America - Full Course": "🇺🇸 EUA",
  "Road Atlanta": "🇺🇸 EUA",
  "Road Atlanta - Full Course": "🇺🇸 EUA",
  "Rudskogen": "🇳🇴 Noruega",
  "Rudskogen Motorsenter": "🇳🇴 Noruega",
  "Sachsenring": "🇩🇪 Alemanha",
  "Sandown": "🇦🇺 Austrália",
  "Sandown International Motor Raceway": "🇦🇺 Austrália",
  "Sebring": "🇺🇸 EUA",
  "Sebring International Raceway": "🇺🇸 EUA",
  "Sebring International Raceway - International": "🇺🇸 EUA",
  "Silverstone Circuit": "🇬🇧 Reino Unido",
  "Silverstone Circuit - Grand Prix": "🇬🇧 Reino Unido",
  "Silverstone Circuit - International": "🇬🇧 Reino Unido",
  "Silverstone Circuit - National": "🇬🇧 Reino Unido",
  "Silverstone GP": "🇬🇧 Reino Unido",
  "Silverstone Intl": "🇬🇧 Reino Unido",
  "Silverstone Natl": "🇬🇧 Reino Unido",
  "Snetterton 200": "🇬🇧 Reino Unido",
  "Snetterton 300": "🇬🇧 Reino Unido",
  "Snetterton Circuit": "🇬🇧 Reino Unido",
  "Snetterton Circuit - 200": "🇬🇧 Reino Unido",
  "Snetterton Circuit - 300": "🇬🇧 Reino Unido",
  "Sonoma": "🇺🇸 EUA",
  "Sonoma Raceway": "🇺🇸 EUA",
  "Sonoma Raceway - Cup Long": "🇺🇸 EUA",
  "Sonoma Raceway - Cup Short": "🇺🇸 EUA",
  "Sonoma Short": "🇺🇸 EUA",
  "Spa": "🇧🇪 Bélgica",
  "Spa Endurance": "🇧🇪 Bélgica",
  "St. Pete": "🇺🇸 EUA",
  "St. Petersburg Grand Prix": "🇺🇸 EUA",
  "Summit Point": "🇺🇸 EUA",
  "Summit Point Raceway": "🇺🇸 EUA",
  "Suzuka": "🇯🇵 Japão",
  "Suzuka International Racing Course": "🇯🇵 Japão",
  "Suzuka International Racing Course - Grand Prix": "🇯🇵 Japão",
  "The Bend GT": "🇦🇺 Austrália",
  "The Bend Intl": "🇦🇺 Austrália",
  "The Bend Motorsport Park": "🇦🇺 Austrália",
  "The Bend Motorsport Park - GT Circuit": "🇦🇺 Austrália",
  "The Bend Motorsport Park - International Circuit": "🇦🇺 Austrália",
  "Thruxton": "🇬🇧 Reino Unido",
  "Thruxton Circuit": "🇬🇧 Reino Unido",
  "Tsukuba": "🇯🇵 Japão",
  "Tsukuba Circuit": "🇯🇵 Japão",
  "Tsukuba Circuit - 2000 Full": "🇯🇵 Japão",
  "VIR Full": "🇺🇸 EUA",
  "VIR Grand": "🇺🇸 EUA",
  "VIR North": "🇺🇸 EUA",
  "VIR South": "🇺🇸 EUA",
  "Virginia International Raceway": "🇺🇸 EUA",
  "Virginia International Raceway - Full Course": "🇺🇸 EUA",
  "Virginia International Raceway - Grand Course": "🇺🇸 EUA",
  "Virginia International Raceway - North Course": "🇺🇸 EUA",
  "Virginia International Raceway - South Course": "🇺🇸 EUA",
  "Watkins Cup": "🇺🇸 EUA",
  "Watkins Glen International": "🇺🇸 EUA",
  "Watkins Glen International - Cup": "🇺🇸 EUA",
  "WeatherTech Raceway at Laguna Seca": "🇺🇸 EUA",
  "WeatherTech Raceway at Laguna Seca - 2026": "🇺🇸 EUA",
  "Willow Springs": "🇺🇸 EUA",
  "Willow Springs International Raceway": "🇺🇸 EUA",
  "Winton": "🇦🇺 Austrália",
  "Winton Motor Raceway": "🇦🇺 Austrália",
  "Winton Motor Raceway - Club Circuit": "🇦🇺 Austrália",
  "Winton Motor Raceway - National Circuit": "🇦🇺 Austrália",
  "Winton National": "🇦🇺 Austrália",
  "Zandvoort": "🇳🇱 Holanda",
  "Zandvoort Chicane": "🇳🇱 Holanda",
  "Zandvoort Natl": "🇳🇱 Holanda",
  "Zolder": "🇧🇪 Bélgica",
};
