//! Catálogo de incidentes de corrida — dados de seed da tabela `incident_catalog`.
//!
//! Extraído da migração v14 original. É puro dado: 54 entradas com os textos de
//! DNF/não-DNF por classe de veículo, formato de corrida e origem do incidente.

use rusqlite::Connection;

use crate::db::connection::DbError;

pub fn seed_incident_catalog(conn: &Connection) -> Result<(), DbError> {
    // INSERT OR IGNORE para idempotência
    // Formato: (id, vehicle_class, race_format, incident_source, trigger_type,
    //           severity_context, weight_sprint, weight_endurance,
    //           dnf_template, non_dnf_template, description_short)
    let entries: &[(
        &str,
        &str,
        &str,
        &str,
        &str,
        &str,
        i64,
        i64,
        &str,
        Option<&str>,
        &str,
    )] = &[
        // ═══ STREETBASED SPRINT MECHANICAL SPONTANEOUS ═══
        (
            "SB_S_MEC_01",
            "StreetBased",
            "Sprint",
            "Mechanical",
            "Spontaneous",
            "Both",
            100,
            0,
            "{driver} abandona com problema no câmbio – sincronizador da 3ª marcha falhou",
            Some("{driver} com dificuldade no câmbio – perdeu ritmo"),
            "Câmbio – sincronizador",
        ),
        (
            "SB_S_MEC_02",
            "StreetBased",
            "Sprint",
            "Mechanical",
            "Spontaneous",
            "Both",
            70,
            0,
            "{driver} abandona por embreagem queimada após largada",
            Some("{driver} sentindo a embreagem patinar – ritmo comprometido"),
            "Embreagem queimada",
        ),
        (
            "SB_S_MEC_03",
            "StreetBased",
            "Sprint",
            "Mechanical",
            "Spontaneous",
            "Both",
            40,
            0,
            "{driver} abandona por falha nos freios – disco rachado",
            Some("{driver} com freios comprometidos – perdendo posições"),
            "Freio – pastilha/disco",
        ),
        (
            "SB_S_MEC_04",
            "StreetBased",
            "Sprint",
            "Mechanical",
            "Spontaneous",
            "Both",
            20,
            0,
            "{driver} abandona por superaquecimento do motor",
            Some("{driver} com temperatura do motor elevada – reduzindo ritmo"),
            "Superaquecimento",
        ),
        (
            "SB_S_MEC_05",
            "StreetBased",
            "Sprint",
            "Mechanical",
            "Spontaneous",
            "Both",
            10,
            0,
            "{driver} abandona por perda de potência – falha no motor",
            Some("{driver} com perda de potência – ritmo comprometido"),
            "Motor – perda de potência",
        ),
        // ═══ STREETBASED ENDURANCE MECHANICAL SPONTANEOUS ═══
        (
            "SB_E_MEC_01",
            "StreetBased",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "Both",
            0,
            100,
            "{driver} abandona com problemas no câmbio",
            Some("{driver} com câmbio engasgando – perdeu ritmo"),
            "Câmbio – sincronizador/garfo",
        ),
        (
            "SB_E_MEC_02",
            "StreetBased",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "Both",
            0,
            70,
            "{driver} abandona por falha no motor – dano interno",
            Some("{driver} com motor perdendo força"),
            "Motor – biela/bronzina",
        ),
        (
            "SB_E_MEC_03",
            "StreetBased",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "Both",
            0,
            70,
            "{driver} abandona por embreagem gasta – sem tração",
            Some("{driver} com embreagem desgastada – tração comprometida"),
            "Embreagem desgastada",
        ),
        (
            "SB_E_MEC_04",
            "StreetBased",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "Both",
            0,
            50,
            "{driver} abandona por superaquecimento – falha no arrefecimento",
            Some("{driver} monitorando temperatura elevada – ritmo reduzido"),
            "Superaquecimento – radiador/bomba",
        ),
        (
            "SB_E_MEC_05",
            "StreetBased",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "Both",
            0,
            40,
            "{driver} abandona por falha elétrica – bateria descarregou",
            Some("{driver} com problemas elétricos intermitentes"),
            "Alternador/bateria",
        ),
        (
            "SB_E_MEC_06",
            "StreetBased",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "Both",
            0,
            40,
            "{driver} abandona por perda de freios",
            Some("{driver} com freios degradados – frenando mais cedo"),
            "Freio – disco/fluido ferveu",
        ),
        (
            "SB_E_MEC_07",
            "StreetBased",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "Both",
            0,
            20,
            "{driver} abandona por quebra do semi-eixo",
            Some("{driver} sentindo vibração na transmissão"),
            "Semi-eixo/cubo de roda",
        ),
        (
            "SB_E_MEC_08",
            "StreetBased",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "Both",
            0,
            10,
            "{driver} abandona por falha na alimentação de combustível",
            Some("{driver} com motor falhando intermitentemente"),
            "Bomba de combustível",
        ),
        // ═══ RACESPEC SPRINT MECHANICAL SPONTANEOUS ═══
        (
            "RS_S_MEC_01",
            "RaceSpec",
            "Sprint",
            "Mechanical",
            "Spontaneous",
            "Both",
            100,
            0,
            "{driver} abandona por falha no câmbio – ficou preso em uma marcha",
            Some("{driver} com câmbio travando – perdeu posições"),
            "Câmbio – garfo/atuador",
        ),
        (
            "RS_S_MEC_02",
            "RaceSpec",
            "Sprint",
            "Mechanical",
            "Spontaneous",
            "Both",
            70,
            0,
            "{driver} abandona por embreagem queimada",
            Some("{driver} com embreagem patinando"),
            "Embreagem queimada",
        ),
        (
            "RS_S_MEC_03",
            "RaceSpec",
            "Sprint",
            "Mechanical",
            "Spontaneous",
            "Both",
            40,
            0,
            "{driver} abandona por falha nos freios – disco rachado",
            Some("{driver} com freios comprometidos"),
            "Freio – disco rachado",
        ),
        (
            "RS_S_MEC_04",
            "RaceSpec",
            "Sprint",
            "Mechanical",
            "Spontaneous",
            "Both",
            20,
            0,
            "{driver} abandona por falha eletrônica – carro em modo de proteção",
            Some("{driver} com eletrônica instável – ritmo irregular"),
            "Eletrônica – sensor/ECU",
        ),
        (
            "RS_S_MEC_05",
            "RaceSpec",
            "Sprint",
            "Mechanical",
            "Spontaneous",
            "Both",
            10,
            0,
            "{driver} abandona por superaquecimento do motor",
            Some("{driver} com temperatura elevada – gerenciando ritmo"),
            "Superaquecimento",
        ),
        // ═══ RACESPEC ENDURANCE MECHANICAL SPONTANEOUS ═══
        (
            "RS_E_MEC_01",
            "RaceSpec",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "Both",
            0,
            100,
            "{driver} abandona por problemas no câmbio",
            Some("{driver} com câmbio apresentando falhas"),
            "Câmbio – garfo/engrenagem/óleo",
        ),
        (
            "RS_E_MEC_02",
            "RaceSpec",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "Both",
            0,
            70,
            "{driver} abandona por embreagem gasta",
            Some("{driver} com embreagem desgastada"),
            "Embreagem desgastada",
        ),
        (
            "RS_E_MEC_03",
            "RaceSpec",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "Both",
            0,
            60,
            "{driver} abandona por falha no motor",
            Some("{driver} com motor perdendo rendimento"),
            "Motor – turbo/biela",
        ),
        (
            "RS_E_MEC_04",
            "RaceSpec",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "Both",
            0,
            50,
            "{driver} abandona por falha elétrica – alternador parou de carregar",
            Some("{driver} com problemas elétricos recorrentes"),
            "Alternador/bateria",
        ),
        (
            "RS_E_MEC_05",
            "RaceSpec",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "Both",
            0,
            40,
            "{driver} abandona por superaquecimento",
            Some("{driver} gerenciando temperatura elevada"),
            "Superaquecimento – radiador/bomba",
        ),
        (
            "RS_E_MEC_06",
            "RaceSpec",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "Both",
            0,
            40,
            "{driver} abandona por perda de freios",
            Some("{driver} com freios degradados"),
            "Freio – disco/fluido",
        ),
        (
            "RS_E_MEC_07",
            "RaceSpec",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "Both",
            0,
            20,
            "{driver} abandona por falha no diferencial",
            Some("{driver} com diferencial apresentando ruídos"),
            "Diferencial – vazamento/travamento",
        ),
        (
            "RS_E_MEC_08",
            "RaceSpec",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "Both",
            0,
            20,
            "{driver} abandona por falha eletrônica",
            Some("{driver} com eletrônica intermitente"),
            "Eletrônica – sensor ABS/TC/ECU",
        ),
        (
            "RS_E_MEC_09",
            "RaceSpec",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "Both",
            0,
            10,
            "{driver} abandona por falha na alimentação de combustível",
            Some("{driver} com motor falhando"),
            "Bomba de combustível",
        ),
        // ═══ ERRO DE COMBUSTÍVEL ENDURANCE (Mechanical/Spontaneous) ═══
        // Resolução 1: usa Mechanical para ser selecionado pelo roll_mechanical existente.
        (
            "SB_E_PIT_02",
            "StreetBased",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "DnfOnly",
            0,
            30,
            "{driver} ficou sem combustível na pista",
            None,
            "Erro de cálculo de combustível",
        ),
        (
            "RS_E_PIT_02",
            "RaceSpec",
            "Endurance",
            "Mechanical",
            "Spontaneous",
            "DnfOnly",
            0,
            30,
            "{driver} ficou sem combustível na pista",
            None,
            "Erro de cálculo de combustível",
        ),
        // ═══ STREETBASED POST-COLLISION (Both formats) ═══
        (
            "SB_COL_01",
            "StreetBased",
            "Both",
            "PostCollision",
            "PostCollision",
            "Both",
            100,
            100,
            "{driver} abandona por pneu cortado após contato",
            Some("{driver} com pneu danificado após contato – perdeu posições"),
            "Pneu cortado",
        ),
        (
            "SB_COL_02",
            "StreetBased",
            "Both",
            "PostCollision",
            "PostCollision",
            "Both",
            70,
            70,
            "{driver} abandona por dano na suspensão após contato – convergência comprometida",
            Some("{driver} com suspensão desalinhada após contato – perdendo ritmo"),
            "Suspensão desalinhada",
        ),
        (
            "SB_COL_03",
            "StreetBased",
            "Both",
            "PostCollision",
            "PostCollision",
            "Both",
            40,
            70,
            "{driver} abandona por superaquecimento – radiador danificado após contato",
            Some("{driver} com temperatura subindo após contato – gerenciando dano"),
            "Radiador furado por detrito",
        ),
        (
            "SB_COL_04",
            "StreetBased",
            "Both",
            "PostCollision",
            "PostCollision",
            "Both",
            40,
            40,
            "{driver} abandona por roda danificada após contato",
            Some("{driver} com roda entortada após contato – vibração no carro"),
            "Roda entortada",
        ),
        (
            "SB_COL_05",
            "StreetBased",
            "Both",
            "PostCollision",
            "PostCollision",
            "Both",
            10,
            40,
            "{driver} abandona por vazamento no arrefecimento após contato",
            Some("{driver} com vazamento detectado após contato"),
            "Mangueira de arrefecimento solta",
        ),
        // ═══ RACESPEC POST-COLLISION (Both formats) ═══
        (
            "RS_COL_01",
            "RaceSpec",
            "Both",
            "PostCollision",
            "PostCollision",
            "Both",
            100,
            100,
            "{driver} abandona por pneu cortado após contato",
            Some("{driver} com pneu danificado após contato"),
            "Pneu cortado",
        ),
        (
            "RS_COL_02",
            "RaceSpec",
            "Both",
            "PostCollision",
            "PostCollision",
            "Both",
            100,
            100,
            "{driver} abandona por dano aerodinâmico – perda crítica de downforce",
            Some("{driver} com dano aerodinâmico após contato – carro instável"),
            "Splitter/difusor danificado",
        ),
        (
            "RS_COL_03",
            "RaceSpec",
            "Both",
            "PostCollision",
            "PostCollision",
            "Both",
            70,
            70,
            "{driver} abandona por dano na suspensão após contato",
            Some("{driver} com suspensão comprometida após contato"),
            "Suspensão desalinhada/entortada",
        ),
        (
            "RS_COL_04",
            "RaceSpec",
            "Both",
            "PostCollision",
            "PostCollision",
            "Both",
            70,
            100,
            "{driver} abandona por superaquecimento dos freios – duto bloqueado",
            Some("{driver} com freios superaquecendo – duto de ar bloqueado"),
            "Duto de freio bloqueado",
        ),
        (
            "RS_COL_05",
            "RaceSpec",
            "Both",
            "PostCollision",
            "PostCollision",
            "Both",
            40,
            70,
            "{driver} abandona por superaquecimento – radiador danificado após contato",
            Some("{driver} com temperatura subindo após contato"),
            "Radiador/intercooler furado",
        ),
        (
            "RS_COL_06",
            "RaceSpec",
            "Both",
            "PostCollision",
            "PostCollision",
            "Both",
            40,
            40,
            "{driver} abandona por roda danificada após contato",
            Some("{driver} com roda entortada após contato"),
            "Roda entortada",
        ),
        (
            "RS_COL_07",
            "RaceSpec",
            "Both",
            "PostCollision",
            "PostCollision",
            "Both",
            20,
            40,
            "{driver} abandona por perda de ABS/controle de tração após contato",
            Some("{driver} sem assistências eletrônicas após contato – cuidado redobrado"),
            "Sensor ABS/TC arrancado",
        ),
        (
            "RS_COL_08",
            "RaceSpec",
            "Endurance",
            "PostCollision",
            "PostCollision",
            "Both",
            0,
            40,
            "{driver} recebe penalidade por iluminação danificada",
            Some("{driver} com faróis danificados – penalidade aplicada"),
            "Farol/luz traseira quebrada",
        ),
        // ═══ STREETBASED DRIVER ERROR SPONTANEOUS ═══
        (
            "SB_S_ERR_01",
            "StreetBased",
            "Both",
            "DriverError",
            "Spontaneous",
            "NonDnfOnly",
            80,
            60,
            "",
            Some("{driver} escapou na saída da curva e perdeu posições"),
            "Saída de pista",
        ),
        (
            "SB_S_ERR_02",
            "StreetBased",
            "Both",
            "DriverError",
            "Spontaneous",
            "NonDnfOnly",
            70,
            50,
            "",
            Some("{driver} rodou na chicane e perdeu posições"),
            "Rodada na chicane",
        ),
        (
            "SB_S_ERR_03",
            "StreetBased",
            "Both",
            "DriverError",
            "Spontaneous",
            "DnfOnly",
            40,
            30,
            "{driver} abandona após erro de pilotagem – saiu da pista",
            None,
            "Erro fatal – saída de pista",
        ),
        // ═══ RACESPEC DRIVER ERROR SPONTANEOUS ═══
        (
            "RS_S_ERR_01",
            "RaceSpec",
            "Both",
            "DriverError",
            "Spontaneous",
            "NonDnfOnly",
            80,
            60,
            "",
            Some("{driver} perdeu a traseira e caiu posições"),
            "Perda de traseira",
        ),
        (
            "RS_S_ERR_02",
            "RaceSpec",
            "Both",
            "DriverError",
            "Spontaneous",
            "NonDnfOnly",
            70,
            50,
            "",
            Some("{driver} errou o ponto de frenagem e perdeu posições"),
            "Frenagem tardia",
        ),
        (
            "RS_S_ERR_03",
            "RaceSpec",
            "Both",
            "DriverError",
            "Spontaneous",
            "DnfOnly",
            40,
            30,
            "{driver} abandona após erro de pilotagem",
            None,
            "Erro fatal – bateu na barreira",
        ),
        // ═══ OPERATIONAL POST SPIN STALL ═══
        (
            "SB_S_PIT_01",
            "StreetBased",
            "Sprint",
            "Operational",
            "PostSpinStall",
            "DnfOnly",
            40,
            0,
            "{driver} rodou e não conseguiu religar o motor",
            None,
            "Rodada com stall",
        ),
        (
            "SB_S_PIT_02",
            "StreetBased",
            "Sprint",
            "Operational",
            "PostSpinStall",
            "DnfOnly",
            60,
            0,
            "{driver} rodou e cravou na brita – não conseguiu sair",
            None,
            "Cravou na brita",
        ),
        (
            "SB_E_PIT_01",
            "StreetBased",
            "Endurance",
            "Operational",
            "PostSpinStall",
            "DnfOnly",
            0,
            40,
            "{driver} rodou e não conseguiu religar",
            None,
            "Rodada com stall",
        ),
        (
            "RS_S_PIT_01",
            "RaceSpec",
            "Sprint",
            "Operational",
            "PostSpinStall",
            "DnfOnly",
            40,
            0,
            "{driver} rodou e não conseguiu religar",
            None,
            "Rodada com stall",
        ),
        (
            "RS_S_PIT_02",
            "RaceSpec",
            "Sprint",
            "Operational",
            "PostSpinStall",
            "DnfOnly",
            60,
            0,
            "{driver} rodou e perdeu tempo de volta – não conseguiu sair da brita",
            None,
            "Cravou na brita",
        ),
        (
            "RS_E_PIT_01",
            "RaceSpec",
            "Endurance",
            "Operational",
            "PostSpinStall",
            "DnfOnly",
            0,
            40,
            "{driver} rodou e não conseguiu religar",
            None,
            "Rodada com stall",
        ),
    ];

    let mut stmt = conn.prepare(
        "INSERT OR IGNORE INTO incident_catalog
         (id, vehicle_class, race_format, incident_source, trigger_type,
          severity_context, weight_sprint, weight_endurance,
          dnf_template, non_dnf_template, description_short)
         VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11)",
    )?;

    for e in entries {
        stmt.execute(rusqlite::params![
            e.0, e.1, e.2, e.3, e.4, e.5, e.6, e.7, e.8, e.9, e.10
        ])?;
    }

    Ok(())
}
